### ISSUE TITLE
Any plans for default-credentials support?

### ISSUE THREAD

**Issue by edinella** [ikhsanalatsary/multer-sharp#1]
Awesome tool.
Do you guys have any plans to add [Google application-default-credentials](https://developers.google.com/identity/protocols/application-default-credentials) support?
Tks so much.

**Comment by ikhsanalatsary** [comment]
Tks @edinella for your question. I read the docs and it looks good to add in this library. PR is welcome also.

**Comment by ikhsanalatsary** [comment]
Hi simnare, thanks for PR, do you test it? And work?

**Comment by simnare** [comment]
I just tested it, works as expected. Without keyFilename prop/env variable defined it expects `GOOGLE_APPLICATION_CREDENTIALS` to be defined.

**Comment by simnare** [comment]
Can we have a new release please?
