### ISSUE TITLE
how to specify a different sharp strategy for cropping?

### ISSUE THREAD

**Issue by gianpaj** [ikhsanalatsary/multer-sharp#11]
First of all, great job on this package!
Works great out the box.

Currently, it's only possible to enable or disable cropping.

Could we add these various sharp crop resizing options?
http://sharp.pixelplumbing.com/en/stable/api-resize/#crop

Thanks

**Comment by ikhsanalatsary** [comment]
hi @gianpaj thanks for your question. I think, you could try to update your sharp package directly to your project cause this package use v0.19. let me know if any news.

**Comment by gianpaj** [comment]
Thanks for the quick reply.

I have newer one but I don't think `multer-sharp` is using that:

```
yarn list --depth=0 |grep sharp
├─ multer-sharp@0.4.1
├─ sharp@0.20.2
```

**Comment by ikhsanalatsary** [comment]
ok, first question, how to reproduce the error above? I see, we need update the code to support other crop options.

**Comment by gianpaj** [comment]
Here you go:

```js
const storage = gcsSharp({
  bucket: '...',
  projectId: '...',
  keyFilename: '....json',
  destination: '',
  acl: 'publicRead',
  filename: (req, file, cb) => {
    const uploadDate = Date.now();
    cb(null, uploadDate.toString());
  },
  sizes: [
    {
      suffix: 'thumb.jpeg',
      width: 700,
      height: 700,
    },
    {
      suffix: '.jpeg',
      width: 1440,
      height: 1440,
    },
  ],
  crop: 'center', // <----- change this to 16
  toFormat: 'jpeg',
});
const upload = multer({ storage });

router
  .route('/upload')
  .post(upload.single('photo'), (req, res, next) => {
    res.status(httpStatus.CREATED).json({ data: req.file });
  });
```

**Comment by ikhsanalatsary** [comment]
ok, got it
