### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by ikhsanalatsary** [ikhsanalatsary/multer-sharp#18]
Some package needs to be updated due to vulnerability

**Comment by arrlancore** [comment]
I'll take this pak

**Comment by ikhsanalatsary** [comment]
ok @arrlancore 👍

**Comment by ikhsanalatsary** [comment]
@Ashwin-Kapes no need to use the emulator, you need to install node js and try to run `npm audit` to see the vulnerable packages
