### ISSUE TITLE
Local Storage Option?

### ISSUE THREAD

**Issue by ronaldlong46** [ikhsanalatsary/multer-sharp#5]
This is just what I need, a way of uploading images then compressing them with sharp, as most pictures taken from smartphones are ~5 MB each. Way too big. I am not a fan of Google Cloud Storage, though, I dug through the docs but didn't find anything. Is there a local storage option?

**Comment by ikhsanalatsary** [comment]
Thanks for your question. Localstorage works only in browser environment. This package is just custom storage for Multer which is run in nodejs / server environment only. There's no localstorage.

**Comment by simnare** [comment]
Can we have a new release with this change?
